#!/usr/bin/python3

import math
import sys

def factorize(num):
    """Factorizes a number into a product of two smaller numbers."""
    for i in range(2, int(math.sqrt(num)) + 1):
        if num % i == 0:
            return f"{num}={i}*{num//i}"
    return f"{num} is prime"

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    filename = sys.argv[1]
    with open(filename) as f:
        for line in f:
            num = int(line.strip())
            print(factorize(num))
